title: Kitchen
lightdash:
  container_width: 480px
  container_height: 480px
views:
  - type: sections
    max_columns: 1
    background:
      image: /api/image/serve/df6d99dadd42ccd63e0d444628af8b75/original
    title: Home
    theme: Google Dark Theme
    badges: []
    sections:
      - type: grid
        cards:
          - clock_style: digital
            clock_size: large
            time_zone: Europe/London
            time_format: '24'
            show_seconds: false
            no_background: true
            type: clock
            grid_options:
              columns: 6
              rows: 1
          - type: tile
            grid_options:
              columns: 6
            entity: input_number.home_comfort_temperature
            name: Home temperature
            show_entity_picture: false
            vertical: false
            features:
              - style: buttons
                type: numeric-input
            features_position: inline
          - type: entities
            entities:
              - entity: light.workshop
                name: Workshop
              - entity: light.living_room_all_lights
                name: Lounge
              - entity: light.dining_room
                name: Dining Room
            show_header_toggle: false
            grid_options:
              columns: 3
              rows: auto
          - type: entities
            entities:
              - entity: light.kitchen_main_lights
                name: Kitchen
              - entity: light.kitchen_counters
                name: Counters
                secondary_info: none
              - entity: light.coffee_bar_light_strip
                name: Coffee Bar
                secondary_info: none
            grid_options:
              columns: 3
              rows: auto
          - type: tile
            entity: cover.kitchen_roof
            name: Roof
            secondary_info: none
            grid_options:
              columns: 6
              rows: auto
