kiosk_mode:
  hide_header: true
views:
  - type: sections
    max_columns: 1
    background:
      image: /api/image/serve/df6d99dadd42ccd63e0d444628af8b75/original
    title: Home
    theme: Google Dark Theme
    badges: []
    sections:
      - type: grid
        cards:
          - type: tile
            grid_options:
              columns: 3
            entity: light.porch
            show_entity_picture: false
            hide_state: true
            vertical: true
            features_position: bottom
          - type: tile
            grid_options:
              columns: 3
            entity: light.entryway
            show_entity_picture: false
            hide_state: true
            vertical: true
            features_position: bottom
          - clock_style: digital
            clock_size: medium
            time_zone: Europe/London
            time_format: '24'
            show_seconds: false
            no_background: true
            type: clock
            grid_options:
              columns: 6
              rows: 1
          - type: tile
            grid_options:
              columns: 12
            entity: input_number.home_comfort_temperature
            name: Radiators
            show_entity_picture: false
            vertical: false
            features:
              - style: buttons
                type: numeric-input
            features_position: inline
          - type: entities
            entities:
              - entity: light.dining_room
              - entity: light.kitchen
              - entity: cover.kitchen_roof
            show_header_toggle: false
            grid_options:
              columns: 6
              rows: auto
          - type: entities
            entities:
              - entity: light.living_room_pendant_light
                name: Pendant
              - entity: light.living_room_cabinets
                name: Cabinets
                secondary_info: none
              - entity: light.living_room_side_table_lamp
                name: Side table
              - entity: light.living_room_floor_lamp
                name: Floor lamp
            grid_options:
              columns: 6
              rows: auto
          - type: button
            name: Other rooms
            icon: mdi:arrow-right-bold
            tap_action:
              action: navigate
              navigation_path: other-rooms
            grid_options:
              columns: 12
              rows: 1
  - type: sections
    background:
      image: /api/image/serve/df6d99dadd42ccd63e0d444628af8b75/original
    max_columns: 4
    title: Other Rooms
    path: other-rooms
    sections:
      - type: entities
        entities:
          - name: Workshop
            entity: light.workshop
          - name: Upstairs Hallway
            entity: light.upstairs_hallway
          - name: Office All Lights
            entity: light.office_all_lights
          - name: Emmetts Room
            entity: light.emmetts_room
          - name: Bathroom
            entity: light.bathroom_2
          - name: Master Bathroom
            entity: light.master_bathroom
          - name: Master Bedroom
            entity: light.master_bedroom
          - name: Master Bedroom Landing
            entity: light.master_bedroom_landing
          - type: button
            name: Back
            icon: mdi:arrow-left-bold
            tap_action:
              action: navigate
              navigation_path: home
            grid_options:
              columns: 12
